name: Integração continua de Java com Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  # Jobs do ambiente de desenvolvimento
  build-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    steps:
    - name: Realiza o checkout do repositório
      uses: actions/checkout@v3
    - name: Configura o JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Compila o projeto com Maven
      run: mvn -B compile --file pom.xml
  
  # Jobs do ambiente de homologação
  build-hmg:
    runs-on: ubuntu-latest
    environment: 
      name: hmg
    needs: build-dev
    steps:
    - name: Realiza o checkout do repositório
      uses: actions/checkout@v3 
      with:
        fetch-depth: 0 
    - name: Configura o JDK 18
      uses: actions/setup-java@v3      
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Testa o projeto com Maven
      run: mvn -B test --file pom.xml

  build-prd:
    runs-on: ubuntu-latest
    environment: 
      name: prd
    needs: build-hmg
    steps:
    - name: Realiza o checkout do repositório
      uses: actions/checkout@v3
    - name: Configura o JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
